'use client';
import {useMemo, useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {BookOpen, Menu, X, Phone, Mail, Award, Monitor, Briefcase, Target, FileText, UserPlus, Download, CreditCard, UserRound, MapPin, Search, CheckCircle2} from 'lucide-react';
import {courses, institute, nav, posts, results} from '../lib/data';

export function Header(){
  const [open,setOpen]=useState(false);
  return <>
    <div className="topbar"><div className="container topbar-inner"><span>Welcome to {institute.name}</span><span className="top-actions">Have any questions? <b>☎ {institute.phone}</b> <b>✉ {institute.email}</b> <span>f</span><span>◎</span><span>▶</span></span></div></div>
    <header className="header"><div className="container header-inner">
      <Link href="/" className="logo" aria-label="Softech home"><span className="logo-mark">S</span><span><b>SOFTECH</b><em>COMPUTER CENTRE</em><small>GANAUR</small></span></Link>
      <nav className="nav">{nav.map(([n,h])=><Link key={h} href={h}>{n}</Link>)}<Link href="/admissions" className="enquire">✈ Enquire Now</Link></nav>
      <button className="menu-btn" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={22}/></button>
    </div></header>
    {open && <div className="mobile-panel"><button onClick={()=>setOpen(false)} className="close"><X/></button>{nav.map(([n,h])=><Link onClick={()=>setOpen(false)} key={h} href={h}>{n}</Link>)}<Link onClick={()=>setOpen(false)} className="enquire" href="/admissions">Enquire Now</Link></div>}
  </>
}
export function Footer(){return <footer className="footer"><div className="container foot-grid"><div><h3>Softech Computer Centre, Ganaur</h3><p>Professional computer education, certification courses, practical lab training and career-focused learning.</p></div><div><h4>Quick Links</h4>{nav.slice(1,6).map(([n,h])=><Link key={h} href={h}>{n}</Link>)}</div><div><h4>Contact</h4><p>{institute.phone}</p><p>{institute.email}</p><p>{institute.address}</p></div></div><div className="copyright">© 2025 Softech Computer Centre, Ganaur. All Rights Reserved.</div><a className="whatsapp" href={`https://wa.me/${institute.whatsapp}`}>♣ Chat on WhatsApp</a></footer>}
export function Layout({children}){return <><Header/>{children}<Footer/></>}

export function HomePage(){return <main>
  <Hero/>
  <FeatureStrip/>
  <section className="container home-split"><CoursesPreview/><Achievements/></section>
  <QuickLinks/>
  <section className="container section"><SectionTitle title="Why Choose Softech?"/><div className="grid3">{['Industry recognized certificate','Experienced trainers','Modern computer lab','Practical assignments','Job assistance','Affordable fees'].map((x,i)=><div className="soft-card" key={x}><CheckCircle2/><h3>{x}</h3><p>Focused training designed for students, professionals and job seekers.</p></div>)}</div></section>
  <Testimonials/>
  <BlogPreview/>
  <FAQ/>
</main>}
function Hero(){return <section className="hero"><div className="hero-bg"><Image src="/images/hero-reference.png" alt="Softech computer education hero" fill priority sizes="100vw"/></div><div className="container hero-content"><div className="hero-copy"><span className="badge">ADMISSION OPEN 2025</span><h1>Build Your Skills<br/>Build Your <strong>Future</strong></h1><p>Join Softech Computer Centre, Ganaur and take the first step towards a successful career.</p><div className="hero-points"><span>♙ Expert Trainers</span><span>⚙ Latest Technology</span><span>✎ Practical Learning</span><span>▥ 100% Job Assistance</span></div><div className="hero-actions"><Link href="/computer-courses" className="btn">Explore Courses ❯</Link><a className="call" href={`tel:${institute.phone}`}>☎ {institute.phone}</a></div></div></div><button className="slider prev">‹</button><button className="slider next">›</button><div className="dots"><span/><span/><span/></div></section>}
function FeatureStrip(){const fs=[['Certification Courses','Govt. & Industry Recognized Certificates',Award],['Experienced Faculty','Learn from Industry Experts',UserRound],['Modern Computer Lab','Fully Equipped with Latest Technology',Monitor],['Placement Assistance','100% Support for Better Career',Briefcase],['Result Oriented Training','Practical Knowledge Better Results',Target]];return <section className="container feature-strip">{fs.map(([a,b,Icon])=><div className="feature" key={a}><Icon/><div><h3>{a}</h3><p>{b}</p></div></div>)}</section>}
function CoursesPreview(){return <section className="panel courses-panel"><div className="panel-head"><h2>▣ Popular <span>Courses</span></h2><Link href="/computer-courses">View All Courses →</Link></div><div className="course-grid">{courses.slice(0,6).map(c=><CourseCard key={c.title} c={c}/>)}</div></section>}
function CourseCard({c}){return <div className="course-card"><div className={'course-icon '+c.color}>{c.icon}</div><h3>{c.title}</h3><p>Duration: {c.duration}</p></div>}
function Achievements(){return <section className="achievement"><div className="ach-top"><h2>Our <span>Achievements</span></h2><div className="stats">{[['12+','Years of Excellence'],['2500+','Students Trained'],['100+','Courses Offered'],['95%','Success Rate']].map(s=><div key={s[1]}><b>{s[0]}</b><small>{s[1]}</small></div>)}</div></div><div className="ach-bottom"><h3>🎓 Shape Your Career With Us</h3><p>Admissions Open for 2025 – Limited Seats!</p><Link className="dark-btn" href="/admissions">Apply Now →</Link></div></section>}
function QuickLinks(){const q=[['Results','Check Your Result',FileText,'/results'],['Online Admission','Apply Online',UserPlus,'/admissions'],['Download Brochure','Course Information',Download,'/computer-courses'],['Fee Structure','View Course Fees',CreditCard,'/admissions'],['Student Login','Access Your Account',UserRound,'/results'],['Contact Us','Get In Touch',Phone,'/contact-us']];return <section className="container quick-strip">{q.map(([a,b,Icon,h])=><Link href={h} className="quick" key={a}><Icon/><span><b>{a}</b><small>{b}</small></span></Link>)}</section>}
function SectionTitle({title,sub}){return <div className="section-title"><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>}
function Testimonials(){return <section className="section light"><div className="container"><SectionTitle title="Student Testimonials"/><div className="grid3">{['Best computer centre in Ganaur. Practical classes helped me a lot.','Teachers explain every topic clearly and provide regular practice.','I completed Tally and got better confidence for accounting jobs.'].map((t,i)=><div className="testimonial" key={t}><p>“{t}”</p><b>{['Ritika','Mohit','Simran'][i]}</b></div>)}</div></div></section>}
function BlogPreview(){return <section className="container section"><SectionTitle title="Latest News & Articles"/><div className="grid3">{posts.map(p=><article className="blog-card" key={p.title}><span>Computer Education</span><h3>{p.title}</h3><p>{p.excerpt}</p><Link href="/blog">Read More →</Link></article>)}</div></section>}
function FAQ(){const items=['Which course is best for beginners?','Do you provide certificates?','Can I apply online?','Is there practical lab training?'];return <section className="container section faq"><SectionTitle title="Frequently Asked Questions"/>{items.map((x,i)=><details key={x}><summary>{x}</summary><p>{i===0?'Basic Computer or CCC is best for beginners.':'Yes. This demo page includes the section; final integrations can be connected later.'}</p></details>)}</section>}

export function InnerPage({title,subtitle,children}){return <main><section className="page-hero"><div className="container"><h1>{title}</h1><p>{subtitle}</p></div></section><section className="container section">{children}</section></main>}
export function AboutPage(){return <InnerPage title="About Us" subtitle="A trusted computer learning centre in Ganaur."><div className="two-col"><div><h2>Welcome to Softech</h2><p>Softech Computer Centre, Ganaur provides career-oriented computer education with practical training, certification courses, modern lab facilities and student-focused support.</p><p>Our mission is to make every student confident with digital skills required for education, jobs and business.</p></div><div className="info-box"><h3>Highlights</h3><ul><li>Experienced faculty</li><li>Practical assignments</li><li>Certification support</li><li>Flexible batches</li></ul></div></div></InnerPage>}
export function CoursesPage(){return <InnerPage title="Computer Courses" subtitle="Choose from job-ready computer courses."><div className="course-list">{courses.map(c=><div className="course-detail" key={c.title}><CourseCard c={c}/><p>{c.desc}</p><Link href="/admissions" className="mini-btn">Apply Now</Link></div>)}</div></InnerPage>}
export function CertificationPage(){const certs=['Govt. Recognized Computer Certificate','Industry Skill Certificate','DCA / ADCA Certification','Tally + GST Certificate','Graphic & Web Designing Certificate','Python Programming Certificate'];return <InnerPage title="Certification Courses" subtitle="Build credibility with professional certification."><div className="grid3">{certs.map(c=><div className="soft-card" key={c}><Award/><h3>{c}</h3><p>Includes training, assessment support and certificate guidance.</p><Link href="/admissions">Enroll Now →</Link></div>)}</div></InnerPage>}
export function ResultsPage(){const [q,setQ]=useState('');const found=useMemo(()=>results.find(r=>r.roll.toLowerCase()===q.toLowerCase()||r.reg.toLowerCase()===q.toLowerCase()),[q]);return <InnerPage title="Results" subtitle="Search demo result by roll number or registration number."><div className="result-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try SFT1001 or REG2025002"/><button>Search</button></div>{q && <div className="result-card">{found ? <><h2>Result Found</h2>{Object.entries(found).map(([k,v])=><p key={k}><b>{k.toUpperCase()}:</b> {v}</p>)}<button onClick={()=>window.print()} className="btn">Print Result</button></> : <p>No demo result found. Try SFT1001, SFT1002 or SFT1003.</p>}</div>}</InnerPage>}
export function AdmissionsPage(){return <InnerPage title="Admissions" subtitle="Apply online for the 2025 batch."><DemoForm type="admission"/><div className="info-box mt"><h3>Required Documents</h3><p>Aadhaar card, photo, previous education proof and mobile number.</p></div></InnerPage>}
export function ContactPage(){return <InnerPage title="Contact Us" subtitle="Get in touch with Softech Computer Centre."><div className="two-col"><DemoForm type="contact"/><div className="info-box"><h3>Contact Details</h3><p><Phone/> {institute.phone}</p><p><Mail/> {institute.email}</p><p><MapPin/> {institute.address}</p><div className="map">Google Map Placeholder</div></div></div></InnerPage>}
function DemoForm({type}){const [sent,setSent]=useState(false);return <form className="form" onSubmit={e=>{e.preventDefault();setSent(true)}}><h2>{type==='admission'?'Online Admission Form':'Send Message'}</h2><input required placeholder="Full Name"/><input required placeholder="Mobile Number"/><input placeholder="Email Address"/>{type==='admission'&&<select><option>Select Course</option>{courses.map(c=><option key={c.title}>{c.title}</option>)}</select>}<textarea placeholder="Message"/><button className="btn">Submit Demo Form</button>{sent&&<p className="success">Demo submitted successfully. Connect this form to email/API later.</p>}</form>}
export function GalleryPage(){return <InnerPage title="Gallery" subtitle="Classrooms, labs, certificates and events."><div className="gallery-grid">{Array.from({length:9},(_,i)=><div className="gallery-item" key={i}>Softech Gallery {i+1}</div>)}</div></InnerPage>}
export function BlogPage(){return <InnerPage title="Blog" subtitle="Computer tips, course updates and career guidance."><div className="grid3">{posts.concat(posts).map((p,i)=><article className="blog-card" key={i}><span>News</span><h3>{p.title}</h3><p>{p.excerpt}</p><Link href="#">Read More →</Link></article>)}</div></InnerPage>}
export function PrivacyPage(){return <InnerPage title="Privacy Policy" subtitle="Demo privacy information."><p>This demo website collects contact/admission details only when users submit forms. Final deployment can connect forms to email, CRM or database as required.</p></InnerPage>}
